import { Router } from 'express';
import * as controller from './admin.controller';
import { validateBody } from './validate';
import { genericSchema } from './admin.schemas';
import { requireAuth, requireRole } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth, requireRole('admin'));
router.post('/drivers-pending', validateBody(genericSchema), controller.drivers_pending);
router.post('/approve-driver', validateBody(genericSchema), controller.approve_driver);
router.post('/live-rides', validateBody(genericSchema), controller.live_rides);
router.post('/risk-alerts', validateBody(genericSchema), controller.risk_alerts);
router.post('/refunds', validateBody(genericSchema), controller.refunds);
export default router;
