import { Router } from 'express';
import * as controller from './admin.controller';
import { validateBody } from './validate';
import { genericSchema } from './admin.schemas';
import { requireAuth, requireRole } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/risk-alerts', requireRole('admin', 'compliance'), validateBody(genericSchema), controller.risk_alerts);
router.get('/stats', requireRole('admin', 'compliance'), controller.platform_stats);
router.post('/list-users', requireRole('admin', 'compliance'), validateBody(genericSchema), controller.list_users);
router.get('/audit-log', requireRole('admin', 'compliance'), controller.audit_log);
router.post('/governance-requests', requireRole('admin', 'compliance'), validateBody(genericSchema), controller.governance_requests);
router.post('/review-governance-request', requireRole('admin', 'compliance'), validateBody(genericSchema), controller.review_governance_request);
router.post('/retention-sweep', requireRole('admin', 'compliance'), validateBody(genericSchema), controller.retention_sweep);
router.get('/backup-plan', requireRole('admin', 'compliance'), controller.backup_plan);
router.post('/drivers-pending', requireRole('admin'), validateBody(genericSchema), controller.drivers_pending);
router.post('/approve-driver', requireRole('admin'), validateBody(genericSchema), controller.approve_driver);
router.post('/live-rides', requireRole('admin'), validateBody(genericSchema), controller.live_rides);
router.post('/refunds', requireRole('admin'), validateBody(genericSchema), controller.refunds);
router.post('/suspend-user', requireRole('admin'), validateBody(genericSchema), controller.suspend_user);
router.post('/update-ticket', requireRole('admin'), validateBody(genericSchema), controller.update_ticket);
export default router;
