import { Router } from 'express';
import * as controller from './kyc.controller';
import { validateBody } from './validate';
import { genericSchema } from './kyc.schemas';
import { requireAuth } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.post('/webhook', validateBody(genericSchema), controller.webhook);
router.use(requireAuth);
router.post('/create-session', validateBody(genericSchema), controller.create_session);
router.post('/status', validateBody(genericSchema), controller.status);
export default router;
