import { Router } from 'express';
import * as controller from './marketplace.controller';
import { validateBody } from './validate';
import { genericSchema } from './marketplace.schemas';
import { requireAuth } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/same-day-dispatch', validateBody(genericSchema), controller.same_day_dispatch);
router.post('/delivery-options', validateBody(genericSchema), controller.delivery_options);
export default router;
