import { Router } from 'express';
import * as controller from './rides.controller';
import { validateBody } from './validate';
import { rideAcceptSchema, rideEstimateSchema, rideRateSchema, rideRequestSchema, rideStartCompleteCancelSchema } from './rides.schemas';
import { requireAuth, requireRole } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/estimate', validateBody(rideEstimateSchema), controller.estimate);
router.get('/history', controller.history);
router.get('/:rideId', controller.detail);
router.post('/request', requireRole('rider'), validateBody(rideRequestSchema), controller.request);
router.post('/accept', requireRole('driver'), validateBody(rideAcceptSchema), controller.accept);
router.post('/start', requireRole('driver'), validateBody(rideStartCompleteCancelSchema), controller.start);
router.post('/complete', requireRole('driver'), validateBody(rideStartCompleteCancelSchema), controller.complete);
router.post('/cancel', requireRole('rider'), validateBody(rideStartCompleteCancelSchema), controller.cancel);
router.post('/rate', requireRole('rider'), validateBody(rideRateSchema), controller.rate);
export default router;
