import { Router } from 'express';
import * as controller from './support.controller';
import { validateBody } from './validate';
import { genericSchema } from './support.schemas';
import { requireAuth } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/create-ticket', validateBody(genericSchema), controller.create_ticket);
router.post('/list-tickets', validateBody(genericSchema), controller.list_tickets);
router.post('/get-ticket', validateBody(genericSchema), controller.get_ticket);
router.post('/reply-ticket', validateBody(genericSchema), controller.reply_ticket);
router.post('/close-ticket', validateBody(genericSchema), controller.close_ticket);
router.post('/refund-review', validateBody(genericSchema), controller.refund_review);
export default router;
