import { Router } from 'express';
import * as controller from './wallet.controller';
import { validateBody } from './validate';
import { genericSchema } from './wallet.schemas';
import { requireAuth } from './auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/balance', validateBody(genericSchema), controller.balance);
router.post('/ledger', validateBody(genericSchema), controller.ledger);
router.post('/cashout', validateBody(genericSchema), controller.cashout);
export default router;
