import { Router } from 'express';
import * as controller from '../controllers/payments.controller';
import { validateBody } from '../utils/validate';
import { genericSchema } from '../schemas/payments.schemas';
import { requireAuth } from '../middleware/auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.post('/stripe-webhook', validateBody(genericSchema), controller.stripe_webhook);
router.use(requireAuth);
router.post('/create-intent', validateBody(genericSchema), controller.create_intent);
router.post('/capture', validateBody(genericSchema), controller.capture);
router.post('/refund', validateBody(genericSchema), controller.refund);
export default router;
