import { Router } from 'express';
import * as controller from '../controllers/payments.controller';
import { validateBody } from '../utils/validate';
import { genericSchema } from '../schemas/payments.schemas';
import { requireAuth } from '../middleware/auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.post('/stripe-webhook', validateBody(genericSchema), controller.stripe_webhook);
router.use(requireAuth);
router.post('/create-intent', validateBody(genericSchema), controller.create_intent);
router.post('/capture', validateBody(genericSchema), controller.capture);
router.post('/refund', validateBody(genericSchema), controller.refund);
router.post('/save-method', validateBody(genericSchema), controller.save_method);
router.post('/list-methods', validateBody(genericSchema), controller.list_methods);
router.post('/set-default-method', validateBody(genericSchema), controller.set_default_method);
router.post('/remove-method', validateBody(genericSchema), controller.remove_method);
router.post('/get-invoice', validateBody(genericSchema), controller.get_invoice);
router.post('/list-invoices', validateBody(genericSchema), controller.list_invoices);
router.post('/list-refunds', validateBody(genericSchema), controller.list_refunds);
export default router;
