import { Router } from 'express';
import * as controller from '../controllers/safety.controller';
import { validateBody } from '../utils/validate';
import { genericSchema } from '../schemas/safety.schemas';
import { requireAuth, requireRole } from '../middleware/auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/sos', validateBody(genericSchema), controller.sos);
router.post('/share-trip', validateBody(genericSchema), controller.share_trip);
router.post('/incident-report', validateBody(genericSchema), controller.incident_report);
router.post('/list-incidents', validateBody(genericSchema), requireRole('admin'), controller.list_incidents);
router.post('/update-incident', validateBody(genericSchema), requireRole('admin'), controller.update_incident);
export default router;
