import { Router } from 'express';
import * as controller from '../controllers/wallet.controller';
import { validateBody } from '../utils/validate';
import { genericSchema } from '../schemas/wallet.schemas';
import { requireAuth } from '../middleware/auth.middleware';
const router = Router();
router.get('/health', controller.health);
router.use(requireAuth);
router.post('/balance', validateBody(genericSchema), controller.balance);
router.post('/ledger', validateBody(genericSchema), controller.ledger);
router.post('/cashout', validateBody(genericSchema), controller.cashout);
router.post('/add-bank-account', validateBody(genericSchema), controller.add_bank_account);
router.post('/list-bank-accounts', validateBody(genericSchema), controller.list_bank_accounts);
router.post('/remove-bank-account', validateBody(genericSchema), controller.remove_bank_account);
router.post('/set-default-bank-account', validateBody(genericSchema), controller.set_default_bank_account);
router.post('/withdraw', validateBody(genericSchema), controller.withdraw);
router.post('/payout-history', validateBody(genericSchema), controller.payout_history);
router.post('/weekly-summary', validateBody(genericSchema), controller.weekly_summary);
export default router;
